src/components/Tooltip/__tests__/Tooltip.spec.js
src/components/Tooltip/index.js

This PR fixes a bug in tooltip component when it wrappers a clickable element, for example, and, it's not possible to clicks in the element because the listeners is not forward by the tooltip component.

fix forward of listeners and other properties in tooltip

---

src/components/Button/Button.stories.js
src/components/Button/__tests__/Button.spec.js
src/components/Button/button.scss
src/components/Button/index.js
src/components/Button/lib.js
src/components/EditorHeader/EditorHeader.vue
src/components/EditorHeader/components/HeaderTitle.vue
src/components/GroupButton/GroupButton.stories.js
src/components/GroupButton/__tests__/GroupButton.spec.js
src/components/Menu/Menu.stories.js
src/components/Menu/index.js
src/components/Modal/SbModal.stories.js
src/components/Modal/SbModalType.vue
src/components/Modal/__tests__/Modal.spec.js
src/components/Modal/modal.scss
src/components/Slideover/Slideover.stories.js
src/components/Slideover/__tests__/Slideover.spec.js
src/components/TextField/textfield.scss
src/components/index.js

In this PR was added to change the prop `type` name to `variant` and adding a prop `type` to be able to modify the `type` of the buttons.
- Adding the new logic to open **SbSLideover** and **SbModal** so when the story is opened.
- Modifying sb-textfield edges in the `:hover` effect.

Update component: sb-button

---

src/components/Modal/SbModal.stories.js
src/components/Modal/SbModal.vue
src/components/Slideover/Slideover.vue

This PR implements a fix to Modal overlay bug in docs pages. When it access this page, all the modals are opened at once, causing a strange behavior. This code is a downgrade to the logic to open the modal in the story by default, because we do not have how to know in which context the story is executed in the confident way.
We tried:
* To upgrade the version to latest (`v6.1.11`), but, the stories is mounting twice.
* To try to use the `location.search` to get the viewMode parameter in iframe URL (workaround in `v6.0`), but, when it move the context, the viewMode does not change properly.

Fix Modal overlay in Storybook docs

---

.github/workflows/tests.yml

I'm opening this PR to fix the bug in the test script, because in the [last PR](https://github.com/storyblok/storyblok-design-system/pull/65) we continued with the list structure but we added the lts version as a string and so the script didn't work.
Now I'm removing the whole version list structure from node and entering just one string, as directed by João.
Any questions I'm available!

INT-4: changing the test script so that the tests run with the node LTS 

---

LICENSE.md
config/globals.js
package.json
src/assets/styles/global.scss
src/components/Menu/index.js
src/components/Popover/index.js
src/components/Slideover/Slideover.vue

This PR is about this task [INT-21](https://storyblok.atlassian.net/browse/INT-21).
**One can test this by following these steps:**
1. Create a brand new nuxt or vue app
2. Install the DS from this branch with this command `yarn add git+https://github.com/storyblok/storyblok-design-system#feature/INT-21`
3. Clone this branch to your machine
4. Run yarn build
5. Copy the files from `dist` folder
6. Paste these files inside the `dist` folder from `node_modules` > `storyblok-design-system` > `dist`
7. These steps are required, because the yarn install from branch doesn't generate these files. This won't happen by installing from npm/yarn official source.
8. Follow the instructions from [here](https://www.storyblok.com/docs/guide/in-depth/design-system) to add the DS on the new app.
9. For …

`INT-21` - Feature/int 21

---

src/components/UploadDialog/UploadDialog.stories.js
src/components/UploadDialog/UploadDialog.vue

This PR is related to this [issue](https://storyblok.atlassian.net/browse/INT-41) and fixes the modal issue on `SbUploadDialog` component, when visualizing it from storybook's docs, like this [link](https://blok.ink/?path=/docs/design-system-components-sbuploaddialog--default).
Note that you cannot interact with the elements that are behind the modal. 
How to test:
- Clone this repository
- Switch to this branch `fix/INT-41-modal-fix-on-storybook-docs`.
- Run `yarn install`
- Run `yarn storybook`
- Go to [localhost](http://localhost:6006/?path=/docs/design-system-components-sbuploaddialog--default) and see the changes

`INT-41` - modal fix on storybook docs

---

src/components/Select/components/SelectInner.vue
src/components/Select/select.scss

In this pull request I fix the problem where some selected fields just sometimes get the selected style.
I also fix the selected text below the icon on the left.
Jira Link: [INT-138: SbSelect has no style for selected items](https://storyblok.atlassian.net/browse/INT-138)
To test this PR, open the design system storybook and click:
Menu > Components > Form > SbSelect >  **Mutiple And Avatars**
Select multiple items and make sure the items are checked in the list.
Menu > Components > Form > SbSelect >  **With Icon**
Select the item and make sure the icon is not over the text.
For any questions I am available.

INT-138[bugfix]: Add style for selected items sbSelect 

---

src/components/Button/button.scss

In this PR I just add one style to the disabled state of all button variations.
Jira Link: [INT-116 - Update button disabled state](https://storyblok.atlassian.net/browse/INT-116)
Go to: https://blok.ink
In **Menu > Components > SbButton**
Check if the disabled state of all variations is with the same style as Nikola informed me in the slack as per the print.
Any questions, I'm available!

 INT-116: Update button disabled state INT-116

---

src/components/Button/button.scss

In this PR I just add one style to the disabled state of all button variations.
Jira Link: [INT-116 - Update button disabled state](https://storyblok.atlassian.net/browse/INT-116)
Go to: https://blok.ink
In **Menu > Components > SbButton**
Check if the disabled state of all variations is with the same style as Nikola informed me in the slack as per the print.
Any questions, I'm available!

INT-116: update button disabled state 

---

src/components/Sidebar/components/ListItem.vue

This PR is needed to fix the storyfront console error described in the parent task:
Error: <svg> attribute viewBox: Unexpected end of attribute.
This was happening because the ListItem, which is the Sidebar submenu, was expecting an icon and in some cases we need the submenu without an icon.
To correct I added a condition to display the SbIcon whenever the component receives information in the icon attribute.
Jira Link: [INT-210 - Add condition in the Sidebar ListItem to show the icon when needed](https://storyblok.atlassian.net/browse/INT-210)
In Menu > Components > Sibebar > Open a doc and open browser console:
In props > listItems remove the icon from one of the objects.
Note that the error described at the beginning of this PR will not be displayed.

INT-210[bugfix]: Add condition in the Sidebar ListItem to show the icon when needed

---

src/components/Avatar/index.js
src/components/Icon/Icon.stories.js

This PR is needed to fix the empty nodes on two components SbIcon and SbAvatar.
Jira Link: [INT-104 - Design System - Empty nodes on blok.ink](https://storyblok.atlassian.net/browse/INT-104)
In Menu > Components > SbAvatar > With Fallback
Check that the icons is displayed.
In Menu > Components > SbIcon > Fallback Icon
Check that the icon is displayed.

 INT-104[bugfix]: fix avatar and icon fallback empty nodes

---

src/components/Slideover/slideover.scss

This PR is needed to fix the bottom padding of the SbSlideOver component, as the footer was not padding.
Jira Link: [INT-189 -  SbSlideOver: Bottom padding is missing](https://storyblok.atlassian.net/browse/INT-189)
In Menu > Components > SbSlideOver 
Make sure the footer has space between the text and the component's border.

INT-189[bugfix]: Change margin bottom the sb-modal-footer in sbSlideOver 

---

src/components/Avatar/index.js
src/components/Icon/Icon.stories.js

This PR is needed to fix the empty nodes on two components SbIcon and SbAvatar.
Jira Link: [INT-104 - Design System - Empty nodes on blok.ink](https://storyblok.atlassian.net/browse/INT-104)
In Menu > Components > SbAvatar > With Fallback
Check that the icons is displayed.
In Menu > Components > SbIcon > Fallback Icon
Check that the icon is displayed.

INT-104[bugfix]: fix avatar and icon fallback empty nodes

---

src/components/Button/button.scss
src/components/Button/index.js

In this PR we disable "SbButton" while "IsLoading" is active. So the user can't trigger another request before everything is loaded.
Jira Link: [INT-24 - Disable SbButton when displaying the load.](https://storyblok.atlassian.net/browse/INT-24)
In Menu > Components > SbButton  > Loading button
Check if it's disabled.

INT-24[feature]: Disable SbButton when displaying the load 

---

src/components/NumberField/numberfield.scss

This PR is needed to fix the border in SbNumberField in Safari.
Jira Link: [INT-12](https://storyblok.atlassian.net/browse/INT-12)
In Menu > Components > Form > SbNumberField  > Default
Check that the borders its ok in Safari

[WIP]bugfix(INT-12): SbNumberForm remove double storke

---

src/components/Sidebar/Sidebar.stories.js
src/components/Sidebar/Sidebar.vue
src/components/Sidebar/sidebar.scss

Had to add a prop to add a custom logo if the customer wants to. The default value for the logo is the Storyblok logo as we have now.
This will be used by us when an organization sets its own logo, for example.

Add logo prop to sidebar

---

src/assets/styles/global.scss
src/components/Sidebar/Sidebar.stories.js
src/components/Sidebar/components/ListItem.vue
src/components/Sidebar/components/lists.js
src/components/Sidebar/sidebar.scss

This PR adds a class `transparent-scroll` to the sidebar which styles the scrollbar on different browsers and also fixes the issue of having a double scrollbar when the sidebar is higher than 100vh.
Here's an example:
https://user-images.githubusercontent.com/26799272/154514968-0a5909a2-07d4-4d1c-8e6c-82d60af82c29.mov
Besides that, I did a refactor on the prop `iconBefore` that was wrong because it was about the icon on the right not on left.

ON-298 - Scrollbar UX problem

---

src/components/Avatar/index.js
src/components/Avatar/utils.js
src/lib/internal-icons.js
src/utils/constants.js

Nikola asked to adapt the avatars:
* The initials avatars will now use the DS colors:
* The avatars background will not use the white background anymore:
* The white border around the fallback is removed, so it's the same size as the initial avatar:

bugfix: colors of the avatars

---

src/directives/tooltip/index.js

Related to a bug STS-10 where the tooltip stays forever on a page.

fix: checks if element is still on page to hide tooltip

---

src/directives/tooltip/index.js

There was still a bug that let the dom element stay on the page. This PR also removes also the dom element and not only the popper instance.

fix: removes tooltip dom element

---

src/components/Datepicker/datepicker.scss

This should fix the following bug, when selecting a year or month in the datepicker. It adds a white background on the list.

fix(datepicker): year background

---

src/directives/tooltip/index.js

This fixes the problem of the tooltips not working on SVG icons. SVG element do not have offsetHeight which causes flickering and the intervall to be triggered. Instead we use clientHeight to check if the cleanup should be triggered.
Related to https://storyblok.atlassian.net/browse/STS-10
Video of bug:
https://user-images.githubusercontent.com/11278408/156342578-a9667be1-9538-4ce8-ac7a-35e88a177998.mov

hotfix(tooltip): tooltips should work on svg icons

---

src/components/Menu/index.js

This allows to navigate submenu by clicking the tab key (additional to arrow up and down).
https://user-images.githubusercontent.com/11278408/156160281-907c0135-8a50-4074-b0a5-b39da175751d.mov

fix(menu): add tab navigation

---

src/components/Sidebar/components/ListItem.vue

This fix these console errors:
As SbIcon always expects an icon as props to work, when this data is passed via a variable that can be or not there it breaks. Alternatively, it should be added a conditional rendering in the SbIcon template: src/components/Icon/index.js to prevent future errors for missing conditional rendering.

fix: add conditional rendering

---

src/components/Select/select.scss

This PR fixes the issue that Ademar reported where all selections were scrolling.
Jira Link: [INT-304: In SBSelect: Remove the scrollbar and check if the large options view works](https://storyblok.atlassian.net/browse/INT-304)
- To test this PR, you first need to change a system preference on mac:
Go to System Preferences > General > Show Scroll bars > Check Always
- Then access the Blok.ink generated by vercel and go to:
Menu > Components > Form > SbSelect > Default
Select an option and verify that the scroll bar is not displayed.
- Still in the SbSelect Default, add a longer description to the option at:
Control > Props > Options
Check that the text does not exceed the limits of the select box.
- Do the same tests for SbSelect > With Icon.
I am available for any questions or …

bugfix(int-304): In SBSelect, remove the scrollbar and check if the large options view works

---

src/components/Select/select.scss

This PR fixes the issue that Ademar reported where all selections were scrolling.
Jira Link: [INT-304: In SBSelect: Remove the scrollbar and check if the large options view works](https://storyblok.atlassian.net/browse/INT-304)
- To test this PR, you first need to change a system preference on mac:
Go to System Preferences > General > Show Scroll bars > Check Always
- Then access the Blok.ink generated by vercel and go to:
Menu > Components > Form > SbSelect > Default
Select an option and verify that the scroll bar is not displayed.
- Still in the SbSelect Default, add a longer description to the option at:
Control > Props > Options
Check that the text does not exceed the limits of the select box.
- Do the same tests for SbSelect > With Icon.
I am available for any questions or …

hotfix(int-304): In SBSelect, remove the scrollbar and check if the large options view works

---

src/components/Datepicker/components/DatepickerDays.vue

This PR adjusts the picker so that the last day of the previous month appears correctly.
Jira Link: [INT-341 - [V2][DesignSystem] - SbDatepicker: the last month appears with 1 day less.](https://storyblok.atlassian.net/browse/INT-341)
Go to:
Menu > Components > Form > SbDatepicker
Check that the last day of the previous month is displaying correctly, for example, open the datepicker and check that the last day of March is the 31st.
Please check some months from different years.
Any questions or suggestions, I'm available!

bugfix(INT-341): Adjusting the datepicker so that the last day of previous month appears

---

src/components/Avatar/avatar.scss
src/components/Select/components/SelectInner.vue

Jira Link: [WORK-284](https://storyblok.atlassian.net/browse/WORK-284)
How to reproduce it:
1 - Access any Space configuration;
2 - Access Workflow options;
3 - In "Defined stage, select a stage and go to settings;
4 - At the “Users/Roles who can change the stage Drafting to the next available stage” option, select “Specific users/roles”and after, Assigned roles and check users;
5 - Use "Storyblok team demo space” space, to do so;
- The user initial is centralized vertically and horizontally.

bugfix(WORK-284): User Profile initials are not centralized to its circle

---

src/components/Tabs/Tabs.stories.js
src/components/Tabs/components/tab.js
src/components/Tabs/tabs.scss

In this PR I add the is-disabled attribute in the sbTab component.
Jira Link: [INT-380 - [DS] Add attrs 'isDisabled' in SbTab ](https://storyblok.atlassian.net/browse/INT-380)
Go in:
https://storyblok-design-system-git-feat-int-380-a-5287b4-storyblok-com.vercel.app/?path=/story/design-system-components-sbtabs--default
Check if there is a disabled tab

feature(INT-380): add attr isDisabled in sbTab

---

src/components/Select/__tests__/Select.spec.js
src/components/Select/components/SelectInner.vue

Jira Link: [INT-387](https://storyblok.atlassian.net/browse/INT-387)
The `isInnerSearchVisible` was returning a number instead of a Boolean, breaking the tests. Now, a Boolean is being returned and the unit tests are working fine.

`INT-387` - fix(sb-select): adding boolean

---

src/components/Tooltip/tooltip.scss

Add work break in SbTooltip.
Jira Link: [INT-344 - [HOTFIX] [Design System] [Directives > Vtooltip > Default] the tooltip text gets incorrectly truncated if the string does not include a space](https://storyblok.atlassian.net/browse/INT-344)
Go to the DS: https://blok.ink/?path=/docs/design-system-directives-vtooltip--default 
Type in a long text without any spaces into the “label” field, examples:
`thisisatxtwithoutanyspaceadded`
`ThisIsAtxtWithoutAnySpaceAddThisIs`
`@txtWithoutAnySpaceAddThisIs`
`@txtWithoutAnySpaceLimitThisIs@txtWithoutAnySpace!!!!!!`
Add too normal long text, for example:
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type …

bugfix(sbTooltip): add word-break int-344

---

src/components/Tabs/tabs.scss

Jira Link: -
Nikola requested to change the padding in the DS to the following:
It's good to test inside the storyfront. There will be a second PR in the storyfront to fix all the tabs to be the same and aligned well:
1. `cd storyblok-design-system && git checkout fix/sb-tabs-padding`
2. Then on the localhost navigate the application and check if everything looks correct where tabs are used
3. You can also compare https://storyblok-design-system-git-fix-sb-tabs-padding-storyblok-com.vercel.app/ and https://blok.ink/
https://user-images.githubusercontent.com/11278408/167393508-c9c4ed2e-3f0f-4fef-8c17-aaa8b948ce02.mov
-  Less padding left and right on sb tabs
- 
-

refactor(tabs): padding update

---

src/components/UploadDialog/UploadDialog.stories.js

This PR fixes modal blocking in SbUploadDialog component docs.
Jira Link: [INT-41 - Error on Design System's showcase for SbUploadDialog](https://storyblok.atlassian.net/browse/INT-41)
Open the SbUploadDialog component Docs in [blok.ink](http://localhost:6006/?path=/docs/design-system-components-sbuploaddialog--default) and check if the modal is inside the iframe without blocking the whole page.
Before correction:
After correction:
Note: The Docs tab zoom doesn't work very well when we disable the inlineStories property. I had to disable it so that the modal wouldn't lock the rest of the screen. The zoom issue is a storybook issue and I couldn't find a solution for it. Given this, I talked to the team and the PO to release this task with this observation.
Any problem, I'm available.

bugfix(sbUploadDialog): Fix modal blocking in SbUploadDialog docs int-41

---

src/components/TextField/textfield.scss

In this PR I add support in css so that the height of the input is at 45px in firefox.
Jira Link: [INT-389 - Input height fix](https://storyblok.atlassian.net/browse/INT-389)
In Firefox, go in:
https://storyblok-design-system-git-bugfix-int-389-1c1d51-storyblok-com.vercel.app/?path=/story/design-system-components-form-sbtextfield--default
Inspect the element and make sure the height is at 45px.
Any questions, I'm here!

bugfix(sbTextField): add support for firefox sbTextField height INT-389

---

src/components/TextField/textfield.scss

Fix text that is overlapping the icons in the input in the Firefox browser.
Jira Link: [INT-397 - [DS]- HOTFIX - Text overlaying icon in SbTextField](https://storyblok.atlassian.net/browse/INT-397)
In Firefox, go to https://storyblok-design-system-5ewvion22-storyblok-com.vercel.app/?path=/story/design-system-components-form-sbtextfield--with-icon
Check that the Sbtextfield text is not overlapping the icons in the Firefox browser.
Any questions, I'm here!

hotfix( int-397): fix text overlaying iconsbTextField

---

src/components/TextField/textfield.scss

Fix text that is overlapping the icons in the input in the Firefox browser.
Jira Link: [INT-397 - [DS]- HOTFIX - Text overlaying icon in SbTextField](https://storyblok.atlassian.net/browse/INT-397)
In Firefox, go to https://storyblok-design-system-git-bugfix-int-397-ab6466-storyblok-com.vercel.app/?path=/story/design-system-components-form-sbtextfield--with-icon
Check that the Sbtextfield text is not overlapping the icons in the Firefox browser.
Any questions, I'm here!

bugfix(int-397): fix text overlaying icon sbTextField

---

src/components/Modal/SbModal.vue

In this PR we reduced the amount of event listener instantiated in SbModal.
Before, when creating the component, the "handleCloseModalByPressingEsc" method was called, so that even without opening the modal it had already been instantiated, now we only call this method when opening the modal and when we close it, we remove the event listener.
Jira Link: [INT-181 - Design System: Remove Event Listener on destroy component](https://storyblok.atlassian.net/browse/INT-181)
In https://storyblok-design-system-git-fix-int-181-re-3696bb-storyblok-com.vercel.app/?path=/story/design-system-components-sbmodal--default:
-  Open modal component in new tab:
- In the new tab, open the browser console and make sure there is only one Listener "keydown" event.
`getEventListeners(window)['keydown']`
- Open …

bugfix(sbModal): INT-181 - remove event listener 

---

src/components/Slideover/Slideover.vue

Access: https://storyfront-develop-git-subtask-work-252-storyblok-com.vercel.app/#/login
- Go to Settings > Users > Add new user
- Click in cancel button below the SbSlideover and check if the animation runs correctly
- Now, clicking on an external cancel button on SbSlideover, does the animation correctly to close the component.

fix(work-252): fixes SbSlideover animation when clicking cancel button outside the component

---

src/components/Pagination/pagination.scss

I solved the problem on the firefox browser and update the style of the select, please check the video in the v2 in this PR => https://github.com/storyblok/storyfront/pull/1896
Style update

style(work-276): update style for the pagination select in all browsers

---

src/components/Minibrowser/Minibrowser.stories.js
src/components/Minibrowser/minibrowser.scss

Jira Link: [STR-974](https://storyblok.atlassian.net/browse/STR-974)
1. In the `Content` tab of a Space create a folder or a Story with a very long slug
2. Open any Story and click on the arrow to open the `Content Browser`
3.  The slug should be displayed with an ellipsis `...` at the end if it is too big.
- This is a small fix for the ticket [STR-942](https://storyblok.atlassian.net/browse/STR-942) in storyfront. This PR prevent the slug to have linebreaks or scroll bars when the slugs are too long.

fix(str-974): One line minibrowser slugs

---

src/components/Menu/Menu.stories.js
src/components/Menu/__tests__/MenuItem.spec.js
src/components/Menu/index.js
src/components/Menu/menu.scss

Jira Link: Not enable
Please see the video bellow:
https://user-images.githubusercontent.com/40925579/172491179-aeb68885-d673-4bec-a197-6fd72d494f60.mov
- Now it's possible to render links inside the `SbMenuItem`

refactor: Change`SbMenuItem` to render a custom tag

---

src/components/Slideover/Slideover.stories.js
src/components/Slideover/slideover.scss

This PR is required so that the sbSlideover title does not overlap the close icon.
Jira Link: [INT-439 - [DS] - In SbSlideover the title and X to close overlap](https://storyblok.atlassian.net/browse/INT-439)
Go in:
https://storyblok-design-system-dgyoiptsl-storyblok-com.vercel.app/?path=/story/design-system-components-sbslideover--default
Set a new big title.

bugfix(INT-439): slideover title overlap icon

---

src/components/Tag/tag.scss

Jira Link: [WORK-354](https://storyblok.atlassian.net/browse/WORK-354)
- Fix tag label display when text is too large and has no spaces

fix(work-354): fix tag label when text is too big without spaces

---

src/components/DataTable/index.js

Jira Link: [WORK-393](https://storyblok.atlassian.net/browse/WORK-393)
Please, check on the PR in the V2 repo, you can see the task and the videos with the problem and test in v2 preview.
Check if the deselect function is working on the `DataTable` only possible on multiple selection mode
- The same, it's a refactor on the function to deselectRows.

bugfix(work-393): update `deselectRow` function to remove the correct row

---

src/components/Select/Select.stories.js
src/components/Select/Select.vue
src/components/Select/components/SelectList.vue

To improve usability, in SbSelect when alowCreate with tags, when the combo is empty, we need to inform what the user should do and therefore instead of displaying the message "Sorry, no result found.", we now display "Start typing to add new tag."
Jira Link: [INT-443 - SbSelect with allow create update](https://storyblok.atlassian.net/browse/INT-443)
- Go in: https://storyblok-design-system-ogtt1ycae-storyblok-com.vercel.app/?path=/story/design-system-components-form-sbselect--allow-create
- Remove all options, leaving the array empty.
- Click on the combo and see if the new message is showing.

bugfix(INT-443): SbSelect with allow create update

---

src/components/Button/Button.stories.js
src/components/Button/index.js
src/components/Menu/Menu.stories.js
src/components/Menu/index.js
src/components/Menu/menu.scss

New parameters in the SbMenuButton:
- **hasIconRight**: Allows the user to use the component without the right arrow icon.
- **iconColor**: Change icon color
New parameters in SbMenu:
- **iconColor**: Change icon color
SbMenuButton, to test the component without the right arrow icon, go to:
https://storyblok-design-system-git-feat-int-452-r-9c57ac-storyblok-com.vercel.app/?path=/story/design-system-components-sbmenu--without-item-right
SbButton, to test the component with another icon color, go to and set a new color in iconColor: 
https://storyblok-design-system-git-feat-int-452-r-9c57ac-storyblok-com.vercel.app/?path=/story/design-system-components-sbbutton--just-icons

task(int-452): Remove icon right in sbMenuButton and add color in icon the button

---

src/components/DropArea/drop-area.scss

This commit improves the `dragleave` event by adding the `pointer-events: none;` to all elements on mouseover.
It also fixes problems with the content size
Jira Link: [STR-1137](https://storyblok.atlassian.net/browse/STR-1137)
Set a small window in the browser (width: 768 px)
1. Open the [sbDropArea page](https://storyblok-design-system-obaejwr4o-storyblok-com.vercel.app/?path=/story/design-system-components-sbdroparea--default)
2. From your file system explorer, select a file and drag it to the Asset area (don’t drop it)
4. Drag the Asset out of the window
5. The overlay should disappear.
6. Reload [SbDropArea page](https://storyblok-design-system-obaejwr4o-storyblok-com.vercel.app/?path=/story/design-system-components-sbdroparea--default)
7. Again, from your file system explorer, select …

bugfix(STR-1137): SbDropArea: Problems with drag and drop

---

src/components/Button/SbButton.vue

You can checkout your DS branch to this PR's branch and test the loading buttons of Storyblok app locally. Here are some examples:
https://user-images.githubusercontent.com/26799272/181383743-f9e74f59-5d19-464f-8bde-ade4f15e49b4.mov
- Keeping the span element which makes the button to the keep the correct height
- 
-

Bugfix: keep the span tag when button has loading state

---

jest.config.js
package.json
setup-jest.js
src/assets/styles/variables.scss
src/components/Accordion/__tests__/Accordion.spec.js
src/components/Datepicker/Datepicker.stories.js
src/components/Datepicker/Datepicker.vue
src/components/Datepicker/__tests__/Datepicker.spec.js
src/components/Datepicker/__tests__/DatepickerDays.spec.js
src/components/Datepicker/components/DatepickerDays.vue
src/components/Datepicker/datepicker.scss
src/components/FormGroup/__tests__/FormGroup.spec.js
src/components/FormItem/__tests__/FormItem.spec.js
src/components/TextField/SbTextField.vue
src/components/TextField/TextField.stories.js
src/components/TextField/__tests__/TextField.spec.js
src/main.js
yarn.lock

In this PR we added the features requested by Nikola, they are:
- Enable the input for the user to type the date respecting the format imposed by the mask.
- Open the calendar by clicking on the calendar icon.
- Remove the clearable icon and allow the user to manually remove the date with the backspace.
- Add a specific style for the current date.
- Change the style of footer buttons and also change the text "Done" to "Apply".
- Add the `disabledPast` prop to disable dates before the current date.
- Add the `minDate` so that the user can enter a minimum viable date.
- Add the `maxDate` so that the user can enter a maximum viable date.
To make the above adjustments possible I also changed the SbTextField and added a new story 'With Mask'.
Jira Link: [INT-512 - DateTime field manual date …

feature(int-512): datetime field date entry

---

src/components/TextField/SbTextField.vue
src/main.js

Removing the v-mask from the global vue and using it as a directive inside the SbTextfield component.
Jira Link: [INT-512](https://storyblok.atlassian.net/browse/INT-512)
Check if the SbTextfield component mask is working properly.

refactor(int-512): remove v-mask globaly

---

package.json
setup-jest.js
src/components/Datepicker/Datepicker.vue
src/components/TextField/SbTextField.vue
src/components/TextField/TextField.stories.js
yarn.lock

In this PR we had to remove the **v-mask** package, because the focus was getting lost, this issue is already mapped and there are 2 issues open in the v-mask package (https://github.com/probil/v-mask/issues/59 and https://github.com/probil/v-mask/issues/465), but as we can't wait for the fix I had to change the package to **maska**.
I recorded this video showing the problem happening:
https://user-images.githubusercontent.com/8209305/187281007-53ff4a9f-76c9-48e6-8b40-8682fcea3999.mov
Jira Link: [INT-512](https://storyblok.atlassian.net/browse/INT-512)
Watch the video and check if the errors shown are no longer happening.

bugfix(int-512): fix mask in sbTextField and SbDatepicker

---

src/components/Avatar/Avatar.stories.js
src/components/Avatar/SbAvatar.vue
src/components/Avatar/utils.js

Jira Link: [WORK-487](https://storyblok.atlassian.net/browse/WORK-487)
Now the avatars indicators will have the same colors, thus removing the problem of when the same avatar is rendered more than once in a list the color does not lead to believe that it is another user
**Before this PR**
**After this PR**
[To see the changes go to this link.](https://storyblok-design-system-git-fix-work-487-storyblok-com.vercel.app/?path=/story/design-system-components-sbavatar--multiple-avatars-with-the-same-color)
- Now the avatar initial colors is not random

fix(work-487): Avatar color problem

---

src/components/Select/Select.vue
src/components/Select/select.scss

This PR fixes the behavior of `multiple` `SbSelect` with `allow-create` prop set to `true`.
Jira Link: [STR-1272](https://storyblok.atlassian.net/browse/STR-1272)
The main steps can be found on the ticket.
**It's important to perform a regression tests on all `Multiple Select` scenarios within the application, to make sure everything is working as expected. These are the points:**
**⚠️  For QA (call me if any help is needed to go through the potential scenarios)**
_Base Select Occurrences_
_SbSelect occurrences_
- When the `SbSelect` is `multiple` and has `allow-create` set to `true`, the value will be properly created also when hitting `Enter` key.

fix(str-1272): fix SbSelect to deal properly with created options when multiple

---

src/components/Pagination/pagination.scss

Jira Link: [WORK-518](https://storyblok.atlassian.net/browse/WORK-518)
1. Access _Storyblok demo space_
2. Navigate to _Activities_
3. Check the page list on the top bottom
4. Make sure big numbers like 100 or 600 do not cut.
**This change will take effect no on _Activities_ page, but all lists with pagination with more than 100 pages available for selection.**
- Reduce the padding of the pagination list item to fit bigger numbers

fix(work-518): fix pagination number list padding

---

src/assets/styles/variables.scss
stories/base/Colors/Colors.stories.js

Jira Link: [ON-839](https://storyblok.atlassian.net/browse/ON-839)
This PR just moves the color from the storyfront project to the DS variables file. [Here](https://storyblok-design-system-git-refactor-on-83-d6f000-storyblok-com.vercel.app/?path=/story/design-system-base-colors--all-colors) is the color:
- move color from storyfront to DS
- 
-

Refactor(ON-839): add blue grey to the DS variables file

---

src/components/Tag/lib.js
src/components/Tag/tag.scss

As part of [this feature](https://storyblok.atlassian.net/browse/ON-817) I had to update the `<SbTag/>` component and add a new type to fit [the UI mockup on Abstract](https://share.goabstract.com/931e8b2e-8aab-46d9-afeb-e800e53a1ba9?mode=build&sha=4a9e28cad76cf6bdb723e1c768719bf3075933ea).
To avoid hardcoded magic values I created a `Map` to list available types for this component. As we are not using TypeScript yet, I also added type definition using **JSDoc** to get IntelliSense on it.
Jira Link: [ON-817](https://storyblok.atlassian.net/browse/ON-817)
https://user-images.githubusercontent.com/16685155/191998740-d1246796-cd84-4277-a53b-1e351d3eb71b.mov
- Go to the Design System
- Open the Components list
- Click on the `<SbTag/>` component
- Select _"success"_ in the `type` dropdown
- …

feat(on-817): add trial period expiration warning to space cards

---

src/components/Select/Select.vue
src/components/Select/components/SelectList.vue
src/components/Select/select.scss
src/directives/index.js
src/directives/infinite-scroll.js

Triggering a load-more event to give the capability to implement an infinite load
Jira Link: [WORK-516](https://storyblok.atlassian.net/browse/WORK-516)
1. click the SbSelect it should show the list of items
2. scroll to the end of the list, it should trigger a load-more event
- Must emit a load-more event when the user scrolls till the end of the list of items

feat: sb select emit a load-more event when the user scroll till the end of the list of items

---

src/components/Datepicker/Datepicker.vue
src/components/Datepicker/datepicker.scss
src/components/TextField/SbTextField.vue

Jira Link: [STR-1374](https://storyblok.atlassian.net/browse/STR-1374)
In this PR, I'm getting back with the clear icon to make it possible to clear the datepicker. Also, as I was checking, it seems that we use the blur event to propagate to the parent component the new value. So, in there, I've just checked if the value is empty (so the user cleared the input) and then do the clear things.
This is the final result:
In the end, it is possible to clear the Datepicker:
* Clearing the textfield input
* Clicking on the Clear icon

hotfix(datepicker): back with clear icon and emit the empty value when the user clears the input

---

src/components/Datepicker/Datepicker.stories.js
src/components/Datepicker/Datepicker.vue
src/components/Datepicker/components/DatepickerDays.vue

In this PR I extend the **isSameOrAfter** and **isSameOrBefore** functions from the **dayjs** package so that the error described in the task does not happen, I added the expected format in the **minDate** and **maxDate** attributes in the documentation and I also refactored two methods that were flagged by sonar lint.
Jira Link: [INT-588 - Design System - Error when filling minDate with the wrong format in documentation](https://storyblok.atlassian.net/browse/INT-588)
https://user-images.githubusercontent.com/8209305/188719776-4055ed5f-89c7-402a-9373-cc37998ea68c.mov

Bugfix(int-588):  Error when filling minDate with the wrong format in documentation

---

src/components/DataTable/DataTable.stories.js
src/components/DataTable/components/SbDataTableBodyRow.vue
src/components/DataTable/data-table.scss
src/components/DataTable/index.js
src/components/DataTable/sharedProps.js

Jira Link: [ON-822](https://storyblok.atlassian.net/browse/ON-822)
For the locked items [go here](https://storyblok-design-system-git-feat-on-822-sh-271bb5-storyblok-com.vercel.app/?path=/story/design-system-components-sbdatatable--locked-item) and check if it's not possible to select the items with the locker items. Also check if the when using the header selection the locked items are not counted to the selected items amount.
For the hiding of the actions menu [go here ](https://storyblok-design-system-git-feat-on-822-sh-271bb5-storyblok-com.vercel.app/?path=/story/design-system-components-sbdatatable--hide-actions-menu) and check if the blue bar (actions menu) is not showing.
- add feature to show a lock icon instead of the checkbox so the locked icons are not selectable
- add prop to …

Feat(ON-822): add feature to show a lock icon instead of checkbox

---

src/components/AvatarGroup/SbAvatarGroup.vue
src/components/AvatarGroup/components/SbMoreAvatars.vue

Jira Link: [ON-857](https://storyblok.atlassian.net/browse/ON-857)
Since no new feature (or feature change) is being introduced in this PR, there is no specific behavior to test.
Just make sure the component still works as in production 🙂 
- The `<SbMoreAvatars/>` click event handler was sent twice. It is fixed with this PR:
https://user-images.githubusercontent.com/16685155/198594404-e708c53d-3330-4599-bd5b-71cfcf87ba3b.mov
https://user-images.githubusercontent.com/16685155/198594552-c355a4a5-49bd-423f-92e9-118cf4c1164c.mov
- No new behavior, the component just sends more data in the click event payload. _(for an additional external need)_**
Linked to [a PR on the _storyfront_ repo](https://github.com/storyblok/storyfront/pull/2625)

fix(on-857): changed SbMoreAvatars click event payload and fixes event emitted twice

---

src/components/Popover/index.js

Jira Link: [STR-286](https://storyblok.atlassian.net/browse/STR-286)
from ticket:
```
can we make sure we always have rounded number, so we don’t get position -64.4333px but -64px.
If we have  64.4333 interface looks blurry
```
We might need to check/test all places where the popover is used. I think this has the potential to add other unwanted behavior.
For more detail, read this documentation about the adaptive behaviour: https://popper.js.org/docs/v2/modifiers/compute-styles/#adaptive

fix(str-286): fix unrounded positioning of popper

---

src/components/Select/Select.vue

This PR fixes the behavior of multiple SbSelect with allow-create prop set to true.
Jira Link: [STR-1475 - Tag: Tag creation is not working](https://storyblok.atlassian.net/browse/STR-1475)
The main steps can be found on the ticket.
**It's important to perform a regression tests on all `Multiple Select` scenarios within the application, to make sure everything is working as expected. These are the points:**
**⚠️  For QA (call me if any help is needed to go through the potential scenarios)**
_Base Select Occurrences_
_SbSelect occurrences_
- When the `SbSelect` is `multiple` and has `allow-create` set to `true`, the value will be properly created also when hitting `Enter` key.

fix(str-1475): fix SbSelect to deal properly with created options

---

src/components/Sidebar/Sidebar.stories.js
src/components/Sidebar/components/ListItem.vue
src/components/Sidebar/components/ListItemInner.vue

To complete task WORK-599 it is necessary to add an icon with tooltip in the sidebar item description and that is why I am opening this PR.
Jira Link: [WORK-713](https://storyblok.atlassian.net/browse/WORK-713)
Go in: https://storyblok-design-system-7yzg9n40q-storyblok-com.vercel.app/?path=/story/design-system-components-sbsidebar--default
Check if one of the sidebar items contains an icon next to the description with the tooltip.

subtask(work-713): add tooltip in sidebar item

---

src/components/DataTable/components/SbDataTableColumn.vue
src/components/DataTable/components/SbDataTableHeaderCell.vue
src/components/DataTable/data-table.scss
src/components/Modal/modal.scss
src/components/Tag/SbTag.vue
src/components/Tag/lib.js
src/components/Tag/tag.scss

Jira Link: [ON-894](https://storyblok.atlassian.net/browse/ON-894)
Using organization owner/admin/member & partner accounts.
- Access to :
- Spaces > [choose a space] > Settings > Users
- Organization > Team Management
- Organization > Spaces > [choose a space] > Manage Users
- Partner Portal > Team Management
- Check it matches [the design in Figma](https://www.figma.com/file/oz3GybPvOkpwebQTWN7ejl/%5BON-855%5D--Update-the-organization's-dashboard-UI?node-id=813%3A5022&t=xO7ZwxVIJtAc9rS8-1).
- Check if the component is working as before and that no regression has been made
- New columns have been added to the users table: 
- SSO
- User status
- The list of spaces in which the user is currently active :
- The actions buttons have been moved to a new dots menu :
- We can now hover over the …

feat(on-894): ✨ users' table UI update

---

src/components/DataTable/components/SbDataTableColumn.vue
src/components/DataTable/components/SbDataTableHeader.vue
src/components/DataTable/components/SbDataTableHeaderCell.vue
src/components/DataTable/index.js
src/components/DataTable/sharedProps.js

Jira Link: [ON-894](https://storyblok.atlassian.net/browse/ON-894)
- Try to set the `isSortIconAlwaysVisible` to `true` and check if the icon is displayed
- There is now a new `prop` to make the caret icon always visible in table headers

feat(on-821): :sparkles: introduces sort icon always displayed in <th> logic

---

src/components/Breadcrumbs/Breadcrumbs.stories.js

Jira Link: [INT-697](https://storyblok.atlassian.net/browse/INT-697)
Please, check the SbBreadcrumbs docs and compare the [production docs](https://blok.ink/?path=/docs/design-system-components-sbbreadcrumbs--default) with [the new docs](https://storyblok-design-system-git-task-int-697-storyblok-com.vercel.app/?path=/docs/design-system-components-sbbreadcrumbs--default).
- I solved typos and improved the texts with the examples to how to use the props and types of `SbBreadcrumbs`
[INT-697]: https://storyblok.atlassian.net/browse/INT-697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[INT-697]: https://storyblok.atlassian.net/browse/INT-697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(int-697): updating docs for SbBreadcrumbs

---

src/components/Accordion/SbAccordion.vue
src/components/AvatarGroup/SbAvatarGroup.vue
src/components/AvatarGroup/components/SbMoreAvatars.vue
src/components/Breadcrumbs/BreadcrumbItem.vue
src/components/Breadcrumbs/BreadcrumbLink.vue
src/components/Datepicker/Datepicker.vue
src/components/GroupButton/SbGroupButton.vue
src/components/GroupButton/group-button.scss

while I was using the SbGroupButton two problems were found
1. There’s a space between the buttons on safari
2. The buttons are not updated when the button's text changes
https://user-images.githubusercontent.com/7618411/209816169-6a6b5c1c-4fea-479c-9d46-69de6edbd415.mov
Jira Link: [WORK-723](https://storyblok.atlassian.net/browse/WORK-723)
- Must not show a space(unless the `hasSpaces` is set to true)
- Must re-render the button if some prop change
[WORK-723]: https://storyblok.atlassian.net/browse/WORK-723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WORK-723]: https://storyblok.atlassian.net/browse/WORK-723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(work-723): sbGroupButton fix component update when changing props

---

src/components/Pagination/components/SbPerPageContainer.vue
src/components/Pagination/pagination.scss

Jira Link: [AR-67](https://storyblok.atlassian.net/browse/AR-67)
https://user-images.githubusercontent.com/16685155/216334797-0e11e09e-bfe4-4062-be14-82b9ff9900af.mov
- The pagination component now wraps into two lines on mobile devices to fit with the viewport width.
[AR-67]: https://storyblok.atlassian.net/browse/AR-67?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(AR-67): 💄 improves pagination mobile UI

---

src/components/Modal/SbModal.stories.js
src/components/Modal/SbModal.vue
src/components/Modal/__tests__/ModalPlugin.spec.js
src/components/Modal/plugin/ModalPlugin.vue

SbPortal uses <Teleport> from Vue 3, this feature has 'disable' attribute to disable default rendering of Teleport in document body.
Therefore, when executing the WORK-814 task, we saw the need to pass the dibabled attribute from SBModal to SbPortal, since we want the delete modal of discussions to be inside the comments box.
Jira Link: [WORK-814](https://storyblok.atlassian.net/browse/WORK-814)
Go to Menu > SbModal > Modal Target >check if the modal is opening inside the div.
[WORK-814]: https://storyblok.atlassian.net/browse/WORK-814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Subtask(work-814): Send the disabled attribute in SbModal to SbPortal

---

src/components/Slideover/slideover.scss

Jira Link: [AR-77](https://storyblok.atlassian.net/browse/AR-77)
https://user-images.githubusercontent.com/16685155/216380651-e2ac8244-afd3-4854-b330-8027810d01bc.mov
- On mobile devices, the `<SbSlideover/>` component should fit the viewport width.
This PR is linked to [another PR on the storyfront repo](https://github.com/storyblok/storyfront/pull/3361)
[AR-77]: https://storyblok.atlassian.net/browse/AR-77?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(AR-77): 💄 improves sb-slideover UI on mobile devices

---

src/components/Sidebar/Sidebar.stories.js
src/components/Sidebar/Sidebar.vue
src/components/Sidebar/components/ListItem.vue

Jira Link: [AR-61](https://storyblok.atlassian.net/browse/AR-61)
https://user-images.githubusercontent.com/16685155/216122691-2e128fc0-da3f-4a23-9488-6574fa3588ea.mov
- The `<SbSidebar/>` component now receives a new **optional** `logoDestinationUrl` prop.
This PR is linked to [another PR on the storyfront repo.](https://github.com/storyblok/storyfront/pull/3355)
[AR-61]: https://storyblok.atlassian.net/browse/AR-61?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(AR-61): 💄 adds redirection to spaces list logic on header logo click

---

src/components/DataTable/index.js
src/components/DataTable/sharedProps.js

This PR is about updating the users table sorting logic to consider pagination (used only in org team page)
Jira Link: [ON-1004](https://storyblok.atlassian.net/browse/ON-1004)
https://user-images.githubusercontent.com/16685155/222822270-615f1283-f1db-4ea7-abf8-9c78a28be642.mov
- Space settings : 
https://user-images.githubusercontent.com/16685155/222822617-6942a8da-c534-4448-b3a4-ea3d4dcd64c9.mov
- Partner portal :
https://user-images.githubusercontent.com/16685155/222822585-e8f9cd0a-a7d3-43c4-b95b-a777cf8fb054.mov
- On the organization team management page, the sorting logic now sorts the whole users list, not just the current page.
This PR is linked [to another PR on the storyfront repo](https://github.com/storyblok/storyfront/pull/3514)
[Pull Request …

feat(ON-1004): :sparkles: updates users table sorting logic to consider pagination

---

src/components/Select/Select.stories.js
src/components/Select/Select.vue
src/components/Select/__tests__/Select.spec.js
src/components/Select/components/SelectInner.vue
src/components/Select/components/SelectList.vue
src/components/Select/components/SelectListItem.vue

I added two new slots to the SbSelect component to help implement this behavior [Allowed-list-for-the-content-type-from-a-folder](https://www.figma.com/file/NWShEZSLMgkvKdNGwmBk4W/%5BWORK-635%5D-Allowed-list-for-the-content-type-from-a-folder?node-id=367-26046&t=OmqStiTS5NUhS6Dk-0)
https://user-images.githubusercontent.com/7618411/226925833-054499fd-9c3c-4911-abe5-5a546273d996.mov
It must not affect the way SbSelect is used now and should not have side effects, only add the possibility to pass custom selected items and custom items for the list.
Jira Link: [WORK-589](https://storyblok.atlassian.net/browse/WORK-589)
- It should behave as before, only new slots were added
[WORK-589]: https://storyblok.atlassian.net/browse/WORK-589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …

feat(work-589): adding 'list-item' and 'selection' slots to the SbSelect component

---

src/components/Accordion/Accordion.stories.js
src/components/Accordion/accordion.scss

Jira Link: [STR-1630](https://storyblok.atlassian.net/browse/STR-1630)
This fixes an issue with the flex layout when the icon is present
Also, now an example of the content info will show by default in Storybook
Before and After example
[STR-1630]: https://storyblok.atlassian.net/browse/STR-1630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(str-1630): fix flex issue and add example content info

---

src/components/Accordion/SbAccordion.vue

Please check the type of change your PR introduces:-->
This PR set the type of the button to "button" so it won't trigger submit when used inside a form
To see the problem in action without the 'button' type specification you can go here: https://github.com/storyblok/storyfront/pull/3654 and test in the develop env: Space > Settings > Webhook > New webhook.
Write in a field and press enter: it will toggle the accordion because these accordion button act as submit as the slideover is wrapped inside a form element

refactor(str-1689): ♻️ make button a simple button

---

src/components/Select/Select.stories.js
src/components/Select/components/SelectInner.vue
src/components/Select/select.scss

When we pass the showCaption prop, if the item does not have an itemCaption, the system is displaying empty parentheses:
Jira Link: [IWORK-1021](https://storyblok.atlassian.net/browse/WORK-1021)
Go to: Form > SbSelect > With Caption Tag
Select item 3, it will not have a caption. Make sure parentheses are not displayed.
Go to: Form > SbSelect > With Caption
Select item 3, it will not have a caption. Make sure parentheses are not displayed.

bugfix(work-1021): remove parentheses in SbSelectInner

---

src/components/Datepicker/Datepicker.vue

Jira Link: [INT-867](https://storyblok.atlassian.net/browse/INT-867)
Please take a look into the video in the task to understand the problem.
You can see the problem reported here https://github.com/storyblok/storyblok/issues/905
- When you select a day the time inside the datepicker is not changed to your `time.now()`
[INT-867]: https://storyblok.atlassian.net/browse/INT-867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bugfix(int-867): Time picker minutes change when selecting another date

---

src/components/DataTable/data-table.scss

Make the table's action bar looks good on mobile devices
Jira Link: [WORK-810](https://storyblok.atlassian.net/browse/WORK-810)
- [] Refactoring (no functional changes, no api changes)
Go to [SbDataTable](https://storyblok-design-system-git-chore-work-810-71beb5-storyblok-com.vercel.app/?path=/story/data-sbdatatable--actions-menu) and make sure the action bar looks good in both mobile and desktop
*Before*
*With this changes* 
- 
[WORK-810]: https://storyblok.atlassian.net/browse/WORK-810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

style(work-810): improving table action bar on small devices

---

src/components/Minibrowser/Minibrowser.vue
src/components/Minibrowser/__tests__/Minibrowser.spec.js

Jira Link: [STR-1654](https://storyblok.atlassian.net/browse/STR-1654)
Check if the SbMinibrowser component works as expected. This PR only adds a prop to prevent the key down enter logic in the minibrowser search that selects the only filtered element.
[STR-1654]: https://storyblok.atlassian.net/browse/STR-1654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(STR-1654): Create preventEnterOnSearch prop in Minibrowser component

---

src/components/Modal/SbModal.vue

This is because sometimes we use the SbModal with a conditional (v-if). With this, the auto overflow is not set because the component disappears from the DOM doing this, we can prevent the error that the scroll in the body keeps wrong after SbModal closing
Jira Link: [STR-1756](https://storyblok.atlassian.net/browse/STR-1756)
Check the SbModal component. Now, when we close the modal or remove the SbModal component from the Vue Component Tree, the overflow property in the `body` will turn out to auto.
[STR-1756]: https://storyblok.atlassian.net/browse/STR-1756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

hotfix(STR-1756): force back the overflow auto in the body element when unmounting the SbModal component

---

src/components/TextField/SbTextField.vue
src/components/TextField/textfield.scss

**Related to https://github.com/storyblok/storyfront/pull/3952**
Jira Link: [WORK-1041](https://storyblok.atlassian.net/browse/WORK-1041)
1. An easy easy to test it is within the context of this very same ticket (WORK-1041)
2. Make sure that, whenever you're adding a new language with the label "Default", the first default one will remain disabled but with red borders when errored
- Replacing the styling of disabled input to use class instead of the _disabled_ attribute, to make sure that when the input is disabled AND with error, the red border prevails
[WORK-1041]: https://storyblok.atlassian.net/browse/WORK-1041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(work-1041): update input text disabled style to use class

---

src/components/BlockUI/BlockUi.vue
src/components/BlockUI/block.scss
src/components/Modal/SbModal.vue

Jira Link: [STR-1606](https://storyblok.atlassian.net/browse/STR-1606)
For this [task](https://storyblok.atlassian.net/browse/STR-1606) I needed to remove the padding on the modal in the mobile viewport, so I made the full width modal work without padding on mobile
[STR-1606]: https://storyblok.atlassian.net/browse/STR-1606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(str-1606): remove padding on mobile when in full width mode

---

src/components/Select/Select.vue
src/components/Select/__tests__/Select.spec.js
src/components/Select/components/SelectInner.vue

Added a new slot called `rightIcon` to the SbSelect in order to handle a use case defined in this design [figma](https://www.figma.com/file/1szETf2YEv9379Zw3sXqRW/%5BWORK-295%5D-Multiple-Workflows?type=design&node-id=2001-77758&mode=design&t=i0Zcf0ZyNDQpbLZs-0)
https://github.com/storyblok/storyblok-design-system/assets/7618411/68d69758-77a4-4ded-9be4-51d2bdff0910
Jira Link: [WORK-1116](https://storyblok.atlassian.net/browse/WORK-1116)
Please check if the `SbSelect` still working as before
- Now should be possible to pass a slot to be used as the right icon
[WORK-1116]: https://storyblok.atlassian.net/browse/WORK-1116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(work-1116): adding a rightIcon slot to the SbSelect component

---

src/components/Button/Button.stories.js
src/components/Header/Header.stories.js
src/components/Header/SbHeader.vue
src/components/Header/__tests__/SbHeader.spec.js
src/components/Header/header.scss
src/components/Header/index.js
src/components/Icon/Icon.stories.js
src/components/IconButton/IconButton.stories.js
src/components/Menu/Menu.stories.js
src/components/Toggle/Toggle.stories.js
src/components/index.js
src/lib/all-icons.js
src/utils/isMobileWidth.ts

feat(header): creating a SbHeader component

---

src/components/Avatar/avatar.scss

This prevents this to happen:
BEFORE:
NOW:

style: fix icon in avatar when size is large

---

src/components/Loading/Loading.stories.js
src/components/Loading/LoadingBlockUi.stories.js

Fix storie in sbLoading when the user are in docs.
Before:
Now:
Go to > Interface > SbLoading
Check if the page is ok.

docs(sbLoading): fix style in sbLoading when the user are in docs

---

src/components/DataTable/data-table.scss

Increases the `z-index` CSS property of the `SbDataTableActions` component so that it sets on top of other components
Jira Link: [WORK-1256](https://storyblok.atlassian.net/browse/WORK-1256)
- `SbDataTableActions` z-index should be `2` to prevent it from being below other absolute elements (see example below)
[WORK-1177]: https://storyblok.atlassian.net/browse/WORK-1177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WORK-1256]: https://storyblok.atlassian.net/browse/WORK-1256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(work-1256): increase SbDataTable actions sticky version z-index

---

src/components/TextField/SbTextField.vue
src/components/TextField/__tests__/TextField.spec.js
src/components/TextField/textfield.scss

Situation:
> When there are limits for characters in some fields, the label “`n` characters remaining” is used incorrectly.
> There should be displayed only when the character limit is close.
Jira Link: [WORK-1073](https://storyblok.atlassian.net/browse/WORK-1073)
- The remaining characters' text should only appear when the limit is close
[WORK-1073]: https://storyblok.atlassian.net/browse/WORK-1073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(work-1073): show remaining character only when limit is close

---

src/components/Select/components/SelectInner.vue
src/components/Select/components/SelectInnerTag.vue

In this PR we added a tooltip for additional items selected when hovering over the + option.
Jira Link: [work-1286](https://storyblok.atlassian.net/browse/WORK-1286)
Go to Menu > Forms > SbSelect > Multiple With Count Labels
Check if the tooltip is shown.

feat(work-1286): add tooltip in tag count

---

src/lib/internal-icons.js

For more details about the feature related to this PR. Please check [this PR](https://github.com/storyblok/storyfront/pull/4423) from the storyfront repo.
Jira Link: ON-1360](https://storyblok.atlassian.net/browse/ON-1360)
The new _"whats-new"_ icon should appear in the DS
- A new icon has been added to the DS :

feat(ON-1360): adds new icon

---

src/components/Modal/SbModal.vue
src/components/Modal/components/SbModalCloseButton.vue

Jira Link: [WORK-1303](https://storyblok.atlassian.net/browse/WORK-1303)
There's not much to test, since this is a purely QA-oriented ticket.
- Add dynamic `data-testid` to the `SbModal` close button falling back to `sb-modal-close-button`
[WORK-1303]: https://storyblok.atlassian.net/browse/WORK-1303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(work-1303): add data-testid to SbModal close button

---

src/components/Datepicker/Datepicker.stories.js
src/components/Datepicker/Datepicker.vue
src/components/Datepicker/components/DatepickerTime.vue

Jira Link: [STR-1711](https://storyblok.atlassian.net/browse/STR-1711)
Go to the [design system](https://storyblok-design-system-git-story-str-1711-f0d333-storyblok-com.vercel.app/?path=/story/forms-sbdatepicker--time-type) to test
Now with the new prop minuteRange you can define a number divisible by 60 to set at what internal the minutes should shown
[STR-1711]: https://storyblok.atlassian.net/browse/STR-1711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

story(STR-1711): ✨  add a customizable minute range for datepicker

---

src/components/Pagination/SbPagination.vue

Related to this Github issue: https://github.com/storyblok/storyblok-design-system/issues/452
Jira Link: [STR-1963](https://storyblok.atlassian.net/browse/STR-1963)
In the storybook doc of the SbPagination, the code for the component should have the proper names for the events:
```
v-on:previous-page
v-on:next-page
```
Events name are changed: `on-previous-page` becomes `previous-page` and `on-next-page` becomes `next-page`
[STR-1963]: https://storyblok.atlassian.net/browse/STR-1963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

♻️  refactor(#452): rename SbPagination events names

---

src/components/DataTable/components/SbDataTableHeader.vue
src/components/Datepicker/Datepicker.vue
src/components/Datepicker/components/DatepickerDays.vue
src/components/Datepicker/components/DatepickerHeader.vue
src/components/Datepicker/components/DatepickerMonths.vue
src/components/Datepicker/components/DatepickerYears.vue
src/components/TextField/SbTextField.vue

In this PRA I add data-testid to the SbDatepicker and SbTextfield components.
Jira Link: [WORK-1388](https://storyblok.atlassian.net/browse/WORK-1388)
Go to preview > Menu > Forms > SbDatepicker
Check if already works. 
Go to preview > Menu > Forms > SbTextField
Check if already works. 
[WORK-1388]: https://storyblok.atlassian.net/browse/WORK-1388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(WORK-1388): add data-testid in datepicker and textfield

---

src/components/Datepicker/datepicker.scss

- Added check for every 4th block to set border bottom
Jira Link: [INT-1077](https://storyblok.atlassian.net/browse/INT-1077)
- Schedule a Publish
- Select day
- Select time, then the border bottom for the minute 00 should be there
[INT-1077]: https://storyblok.atlassian.net/browse/INT-1077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(int-1077): datepicker schedule time last block

---

src/components/Modal/SbModal.vue

Please have a look at the code change to get the explanation 🙂 
Jira Link: [ON-1500](https://storyblok.atlassian.net/browse/ON-1500)
- Open the _"What's New"_ modal by clicking on the _"What's New"_ shortcut in the sidebar
- Once the modal is open, hit the ESC key on your keyboard
- The modal should close
- The modal now closes when the user hits the ESC key on his keyboard
[ON-1500]: https://storyblok.atlassian.net/browse/ON-1500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

:bug: fix(ON-1500): adds Esc key listener when is-open is true on created hook

---

.storybook/preview.css
src/components/UploadDialog/UploadDialog.stories.js
src/components/UploadDialog/UploadDialog.vue
src/components/UploadDialog/upload-dialog.scss

Jira Link: [STR-2000](https://storyblok.atlassian.net/browse/STR-2000)
https://storyblok-design-system-git-task-str-2000-9b341b-storyblok-com.vercel.app/?path=/docs/interface-sbuploaddialog--documentation
The progress bar should not be rounded:
BEFORE:
NOW:
[STR-2000]: https://storyblok.atlassian.net/browse/STR-2000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(STR-2000): fix rounded corner on the upload progress bar

---

src/components/Menu/MenuGroup.vue

On this PR we add `data-testid` to the `src/components/Menu/MenuGroup.vue` component to cover what was requested on this [PR](https://storyblok.atlassian.net/browse/WORK-1263)
Jira Link: [WORK-1263](https://storyblok.atlassian.net/browse/WORK-1263)
https://github.com/storyblok/storyblok-design-system/assets/7618411/bf4a4af7-9105-438c-8473-9171bd18a2d9
- No new behavior, the markup only need to have the new `data-testid`s
[WORK-1263]: https://storyblok.atlassian.net/browse/WORK-1263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(work-1263): adding data-testid to the MenuGroup component

---

src/components/DataTable/__tests__/DataTable.spec.js
src/components/DataTable/components/SbDataTableHeader.vue

fixes: #485
- added unit test to prevent the bug resurfacing
- all unit tests pass
- table heads now align with the content on single-select mode in tables
ref: https://github.com/storyblok/storyblok-design-system/issues/485

fix: add empty <th> in single select SbDataTable

---

.github/workflows/tests.yml
src/components/TextField/SbTextField.vue

We need to show a tooltip for the right icon of the SbTextfield
Jira Link: [SHAPE-14](https://storyblok.atlassian.net/browse/SHAPE-14)
Should be possible to show a tooltip for the icon right
[SHAPE-14]: https://storyblok.atlassian.net/browse/SHAPE-14?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

task(shape-14): sbTextField - adding the capability to pass the icon right description

---

src/components/Sidebar/sidebar.scss

Jira Link: [ON-1601](https://storyblok.atlassian.net/browse/ON-1601)
As some icons don't have 24px of height, when using them in the sidebar the sidebar items end up having a smaller height. For example:
By setting a `min-height` of 24px, like we do for the `min-width`, all icons will be the same:
- add min-height property to sb-icon on the sidebar
- 
- 
[ON-1601]: https://storyblok.atlassian.net/browse/ON-1601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

style(on-1601): add min-height to sidebar icons

---

src/lib/internal-icons.js

The color of the sidebar-ideas icon is wrong, now it's always white as if it is selected
it should be kind of gray and just turn white on hover or when the item is active like the others
https://github.com/storyblok/storyblok-design-system/assets/7618411/05926610-087b-4448-acb5-45839feb9e7a
Jira Link: [SHAPE-6](https://storyblok.atlassian.net/browse/SHAPE-6)
- 
- 
- 
[SHAPE-6]: https://storyblok.atlassian.net/browse/SHAPE-6?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(shape-6): fix sidebar-ideas internal icon

---

src/components/EditorHeader/__tests__/HeaderTitle.spec.js
src/components/EditorHeader/components/HeaderTitle.vue

Jira Link: [SHAPE-55](https://storyblok.atlassian.net/browse/SHAPE-55)
Nothing should be changed in the SbHeaderTitle component. The PR adds support for a default slot in this component.
[SHAPE-55]: https://storyblok.atlassian.net/browse/SHAPE-55?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(shape-55): add default slot to the SbHeaderTitle component

---

src/components/Select/components/SelectInner.vue

This PR should not change anything in the end. When I was testing a component that uses this one I figured out that there was a data variable that seemed not to be necessary. So, this PR removes the reference to it through the code. For testing, you can interact with the SbSelect component and use the option: `use-avatars` that enables the avatars inside the select.

refactor(shape-57): remove the reference to showAvatar data in the SelectInner component
