storyblok/storyblok-design-system

src/components/Breadcrumbs/breadcrumbs.scss
src/components/Button/Button.stories.js
src/components/Button/button.scss
src/components/Button/index.js
src/components/GroupButton/GroupButton.stories.js
src/components/GroupButton/group-button.scss

Implement some adjusts in style to align to design.

Update components: sb-button, sb-group-button and sb-breadcrumbs

---

src/components/Avatar/Avatar.stories.js
src/components/Avatar/__tests__/Avatar.spec.js
src/components/Avatar/index.js
src/components/AvatarGroup/avatar-group.scss
src/components/AvatarGroup/index.js

Implement some features in `SbAvatar` and `SbAvatarGroup` components:
* update the logic to open the More Avatars Dropdown: use click/touch event instead of hover;
* add `bgColor` property in `SbAvatar`;
* use this property to set a pattern background in `SbAvatarGroup`;

Update components: sb-avatar and sb-avatar-group

---

.eslintrc.js
src/components/Pagination/Pagination.stories.js
src/components/Pagination/__tests__/Pagination.spec.js
src/components/Pagination/components/containers.js
src/components/Pagination/components/index.js
src/components/Pagination/components/modifiers.js
src/components/Pagination/components/shared.js
src/components/Pagination/index.js
src/components/Pagination/pagination.scss
src/components/Pagination/utils.js

Implement the `SbPagination` component

New component: sb-pagination

---

src/assets/styles/global.scss
src/assets/styles/variables.scss
src/components/Avatar/avatar.scss
src/components/AvatarGroup/avatar-group.scss
src/components/Badge/badge.scss
src/components/Breadcrumbs/breadcrumbs.scss
src/components/Button/button.scss
src/components/GroupButton/group-button.scss
src/components/Icon/icon.scss
src/components/Link/link-button.scss
src/components/Loading/loading.scss
src/components/Notification/Notification.stories.js
src/components/Notification/notification.scss
src/components/Pagination/pagination.scss
src/components/Sidebar/Sidebar.stories.js
src/components/Sidebar/sidebar.scss
src/components/Tabs/tabs.scss
src/components/Tag/tag.scss
src/components/Tooltip/Tooltip.stories.js
src/components/Tooltip/tooltip.scss
stories/base/Colors/Colors.stories.js
stories/base/Colors/colors.scss
stories/base/Typography/typography.scss

In this PR Font sizes have been updated and color names have been added to all components

Update css measurements

---

src/components/Datepicker/Datepicker.stories.js
src/components/Datepicker/Datepicker.vue
src/components/Datepicker/__tests__/Datepicker.spec.js
src/components/Datepicker/__tests__/DatepickerYears.spec.js
src/components/Datepicker/components/DatepickerMonths.vue
src/components/Datepicker/components/DatepickerTime.vue
src/components/Datepicker/components/DatepickerYears.vue
src/components/Datepicker/datepicker.scss

Fix component: datepicker z-index

---

.github/workflows/tests.yml
src/components/Slideover/Slideover.stories.js

This PR fixes the bug in the deploy branch of the develop where the arguments were not correctly declared in the Slideover component's storie.
Making this adjustment was necessary to continue task [INT-4.](https://storyblok.atlassian.net/browse/INT-4)
Any questions I'm available

INT-4:  Fix error in develop build

---

README.md
src/components/Button/__tests__/Button.spec.js
src/directives/tooltip/__tests__/VTooltip.spec.js

This PR was opened for [this task,](https://storyblok.atlassian.net/browse/INT-15) where the user did not have information on how to use the Storyblok design system in their project.
To improve the usability of the developers themselves I added [this link](https://www.storyblok.com/docs/guide/in-depth/design-system) which explains how to use DS in the project's README.
Jira Link: [INT-15: Update the project's Readme](https://storyblok.atlassian.net/browse/INT-15)
To test, make sure you have the USAGE in README.md
The readme.md should contain how to use the Storybook design system package.
For questions or suggestions, I am available!

INT-15 : Update the project readme

---

src/components/UploadDialog/UploadDialog.stories.js
src/components/UploadDialog/UploadDialog.vue

- Added inlineStories: false on UploadDialogStories to render the modal correctly on strybook's docs.

fix(ds): modal fix on storybook

---

src/components/Notification/notification.scss
yarn.lock

To solve this problem I added a fixed font size of 24px in the sbNotification title.
Jira Link: [INT-13: In StoryBlok's Design System, in SbNotification, update size to 24px](https://storyblok.atlassian.net/browse/INT-13)
To test this PR, open the design system storybook and click:
Menu > Components > SbNotification
After that, check the font size of the sbNotification title.
For any questions I am available.

INT-13 [fix]: Update size title the sbNotification 

---

README.md

This PR is about: [INT-61](https://storyblok.atlassian.net/browse/INT-61)
We gonna provide Vue 3 compatibility in a future version, updated readme to notice that information for our users.

`INT-61` - Updated compatibility in readme

---

README.md
package.json
src/components/Datepicker/Datepicker.stories.js
src/components/Datepicker/Datepicker.vue
src/components/Datepicker/__tests__/Datepicker.spec.js
src/components/Datepicker/components/DatepickerHeader.vue

- Making changes from request changes
- Fixing the README

fix(ds): request changes

---

src/components/Tabs/Tabs.stories.js
src/components/Tabs/components/tab.js
src/components/Tabs/tabs.scss

This PR implements an left icon to SbTab.
Jira Link: [WORK-156 -  DS: Add icon to SbTab](https://storyblok.atlassian.net/browse/WORK-156)
Should add a property icon into SbTab with a value corresponding to an icon already in DS

WORK-156[feature]: Adds left icon to SbTab

---

src/components/Tabs/tabs.scss

Just a little fix to position correctly the edit icon.

WORK-156[fix]: Adjusts edit icon position

---

src/components/Select/components/SelectInner.vue
src/components/Select/select.scss

This PR is necessary to correct the selected item with icon, because when selecting an item in SbSelect with icon the text was getting out of the text.
Jira Link: [INT-188 - SbSelect with icon: Layout is broken when selecting the item](https://storyblok.atlassian.net/browse/INT-188)
In Menu > Components > Form > SbSelect  > With Icon
Select an item and check if it will be correct.

INT-188[bugfix]: Change style for selected items with icon in SbSelect 

---

src/components/NumberField/numberfield.scss

This PR is needed to fix the border in SbNumberField in Safari.
Jira Link: [INT-12](https://storyblok.atlassian.net/browse/INT-12)
In Menu > Components > Form > SbNumberField  > Default
Check that the borders its ok in Safari

INT-12[bugfix]: Fixed border the sbNumberField in safari

---

src/lib/internal-icons.js

Jira Link: [WORK-2](https://storyblok.atlassian.net/browse/WORK-2)
I added a new icon on DS

story(work-2): Adding a new icon

---

src/components/Select/components/SelectList.vue

This PR is needed to fix the problem that was happening when searching in select, the dropdown box blinked when searching for an item. Here's the video showing the bug:
https://user-images.githubusercontent.com/8209305/154533038-f6e85f84-6ed2-4d4a-81a8-732be8eb3547.mov
Jira Link: [INT-233: [DS] Dropdown needs to improve the search, it’s flickering](https://storyblok.atlassian.net/browse/INT-233)
In Menu > Components > Form > SbSelect > Lazy search
Search for an item and make sure the dropdown box is not flickering
Any problems I am available!

bugfix(int-233): [DS] Dropdown needs to improve the search, it’s flickering

---

src/components/Sidebar/Sidebar.stories.js
src/components/Sidebar/Sidebar.vue
src/components/Sidebar/components/ListItem.vue
src/components/Sidebar/components/lists.js
src/components/Sidebar/sidebar.scss

Added a background for the menu option that has children items, reduced the top and bottom paddings for the logo and added a fade effect at the bottom when sidebar has a scrollbar. Also refactored the sidebar css to unnest it.
https://user-images.githubusercontent.com/26799272/155142535-cc7bafe3-278f-4513-ba67-e8af48d22b7d.mov

ON-302: Changes on sidebar component

---

src/components/TextField/textfield.scss

Jira Link: [INT-261](https://storyblok.atlassian.net/browse/INT-261)
Check is SbSelect component's input field font's size is 14px.
- The SbSelect component's input's font should be 14px size.

fix(int-261): font size

---

src/components/DataTable/DataTable.stories.js
src/components/DataTable/components/SbDataTableActions.js
src/components/DataTable/data-table.scss
src/components/DataTable/index.js
src/mixins/window-resize-observer.js

Jira Link: [WORK-230](https://storyblok.atlassian.net/browse/WORK-230)
Go to SbDataTable > Actions Menu, sets a number into hideLabelActionsBreakpoint property, select a row into table and resize the window until hide the action buttons label.
- Now we have a new property on SbDataTable: hideLabelActionsBreakpoint
- If the window is smaller than the value set, hides the action buttons label and adds a tooltip to the button (on hover)
- Button 'Cancel' now is 'Clear' (and changed to left side)
- Emits the selected rows

subtask(WORK-230): table actions changes

---

src/components/DataTable/components/SbDataTableBody.js
src/components/DataTable/index.js

Jira Link: [WORK-207](https://storyblok.atlassian.net/browse/WORK-207)
- Outputs selected rows as table order, not selection order
- Emits cancel event

subtask(WORK-207): SbDataTable changes

---

src/components/Icon/Icon.stories.js
src/components/Icon/icon.scss
src/components/Icon/index.js
src/components/Modal/components/SbModalHeader.vue

Jira Link: -
Check out the icon in the storybook, now you can select a background color, if you want to use it.
- 
- 
-

feature(icon): background color

---

src/components/Modal/modal.scss

Jira Link: N/A
This fixes an issue where group buttons have a space (even when the spaces prop is false) in the modal.

task(STR-780): group button in modal fix

---

src/components/Select/Select.stories.js
src/components/Select/Select.vue
src/components/Select/__tests__/Select.spec.js
src/components/Select/components/SelectInner.vue
src/components/Select/components/SelectList.vue
src/components/Select/components/SelectListItem.vue
src/components/Select/select.scss

I added a possibility to render path on SbSelectList
Jira Link: [WORK-63](https://storyblok.atlassian.net/browse/WORK-63)
Go for the last story on SbSelect section on Storybook, and check if the select has path bellow the item value
In the video bellow you can see a explanation of this feature 😄 
https://user-images.githubusercontent.com/40925579/162491878-17ef9f8c-2bae-4cde-b1bb-0ae206e09cd4.mov
- Now its possible to render the path in SbSelect

story(work-63): Display path on `SbSelect`

---

src/assets/styles/variables.scss
src/components/Notification/index.js
src/components/Notification/notification.scss

Jira Link: -
Nikola said to update the DS component to this design:
- allow default slot
- fix formatting
- remove x on full width component
- reduce size of icon

fix: various issues on sb-notification

---

src/components/Select/Select.stories.js
src/components/Select/Select.vue
src/components/Select/__tests__/Select.spec.js
src/components/Select/components/SelectInner.vue
src/components/Select/components/SelectList.vue
src/components/Select/components/SelectListItem.vue
src/components/Select/select.scss

Jira Link: N/A
This PR is only a improvements of the SbSelect prop name, has not changes on design or features.
If you want to see the main PR for this task, go for this PR => #168 
The same

chore: Update `SbSelect` prop name 

---

src/lib/internal-icons.js

Jira Link: [WORK-168](https://storyblok.atlassian.net/browse/WORK-168)
- It fixes the color of the new `play-circle` icon

fix: play-circle icon color

---

src/components/Radio/radio.scss

Jira Link: [WORK-168](https://storyblok.atlassian.net/browse/WORK-168)
`sb-radio` label color change when the input is `disabled`

feat(sb-radio): update disabled state label color

---

src/components/NumberField/numberfield.scss

- Adjusting padding to match 45px height.
Jira Link: [INT-275](https://storyblok.atlassian.net/browse/INT-275)
- 
- 
-

feat(int-275): adjusting padding

---

src/components/TextField/textfield.scss

- Adjusting padding to match 45px height.
Jira Link: [INT-271](https://storyblok.atlassian.net/browse/INT-271)
- 
- 
-

feat(int-271): adjusting padding

---

src/components/DataTable/__tests__/DataTable.spec.js
src/components/DataTable/index.js

Jira Link: [INT-266](https://storyblok.atlassian.net/browse/INT-266)
Removing the loading spinner from `SbDatatable`.
No loading spinner while loading data.

`INT-266` - Style/int 266 remove spinner from table

---

src/components/Accordion/accordion.scss

Jira Link: [STR-862](https://storyblok.atlassian.net/browse/STR-862)
The accordion should only show the settings icon on hover in closed state.

feat(str-908): update accordion to only show on hover

---

src/components/Tabs/tabs.scss

Reverts storyblok/storyblok-design-system#197
Reverting because @fariacc found an issue and I merged the branch by mistake.

Revert "refactor(tabs): padding update"

---

src/components/Accordion/accordion.scss

Jira Link: [STR-862](https://storyblok.atlassian.net/browse/STR-862)
These are some updates Nikola requested to the accordion

subtask(str-862): update accordion

---

src/components/Accordion/Accordion.stories.js
src/components/Accordion/Accordion.vue
src/components/Accordion/accordion.scss

Jira Link: -
Check the deployed link for the new options. The updates were made to make this design possible:
- adds a `noHighlight` to remove the highlighting when it's open 
- adds a option `noBorder` to remove the top and bottom border
-  adds a option `noPadding` to reduce the left and right padding

feature(accordion): styling updates

---

src/components/Select/Select.vue

- SbSelect when filterable option is true only emits the value inside the input after select an item in search list. With this change, now we emits the value typed on search input.

feat(SbSelect): emits search input text

---

src/components/Avatar/SbAvatar.vue

fix(avatar): fix conditionals

---

src/components/Avatar/SbAvatar.vue
src/components/Avatar/avatar.scss
src/lib/internal-icons.js

- Fix the avatar fallback image styling
- 
-

fix(avatar): address avatar fallback image style

---

src/components/AvatarGroup/avatar-group.scss
yarn.lock

- Adjustment for avatar group border thickness.
Jira Link: [INT-451](https://storyblok.atlassian.net/browse/INT-451)
- Check for avatar group border's thickness. They should not have a blank space between avatar and its border.

`INT-451` - fix(int-451): avatar group border

---

src/components/Pagination/Pagination.stories.js
src/components/Pagination/index.js

- Added events to handle previous and next events
- Improved docs.
Jira Link: [INT-457](https://storyblok.atlassian.net/browse/INT-457)
Listen to the new `onPreviousPage` and `onNextPage` events. They should be triggered when one clicks either the previous or next buttons in the SbPagination component.
New event listeners.
- Added two new events
- Improved the docs from storybook

`INT-457` - feat(int-457): improving events on SbPagination

---

src/components/Button/Button.stories.js

Fix icon color in storie.
Jira Link: [INT-452 - fix stories ](https://storyblok.atlassian.net/browse/INT-452)
Go to SbButton, change the icon color and check if the icon on the right has also been changed.
Note: the sbLoading icon is not changed because it is based on the button variant.

doc(SbButton): int-452 fix stories

---

src/components/FormItem/FormItem.stories.js
src/components/FormItem/SbFormItem.vue
src/components/FormItem/form-item.scss
src/components/Tabs/__tests__/Tabs.spec.js
yarn.lock

Jira Link: [STR-966](https://storyblok.atlassian.net/browse/STR-966)
This adds the ability to show a * next to the label of a required field.

feat(str-1102): add required prop for label of formitem

---

src/components/TextField/SbTextField.vue
src/components/TextField/textfield.scss

Jira Link: [STR-966](https://storyblok.atlassian.net/browse/STR-966)
Some of the * to be added were not using SbFormItem, so I also need to add the * in the SbTextField.
While doing this, I noticed that the Account Management just has the * in the translation string. I would suggest that I can change those strings to use this new change in the SbTextField.

Subtask/str 1120 Add required * to SbTextField

---

src/components/Accordion/AccordionTransition.vue
src/components/Accordion/SbAccordion.vue
src/components/Accordion/accordion.scss
src/components/Accordion/index.js

Jira Link: -
This refactors the Accordion component to Vue 3 like we have on the Vue 3 update branch [here](https://github.com/storyblok/storyblok-design-system/pull/258) 
To test you can compare this deployment to the blok ink
- 
- 
-

refactor(accordion): to vue 3 syntax

---

src/lib/internal-icons.js

Jira Link: [STR-1142](https://storyblok.atlassian.net/browse/STR-1161)
1. Open all the icons
2. Check If the reload icon is there
- This PR adds the reload icon to the Design System

feat(str-1161): Add the reload icon to the design system

---

src/components/Accordion/accordion.scss

Jira Link: [STR-1171](https://storyblok.atlassian.net/browse/STR-1171)
1. Open a story
1. Add a group field-type
1. Add a Datetime field type
1. Associate the Datetime to the group
1. Add other field types after the group
1. Save the schema
1. Go to the content form
1. Click on the Datetime field-type
1. The date picker should be displayed on top of the fields below

hotfix(str-1171): Support Ticket [SD-91] user is not able to see date/time fields as they cannot scroll down

---

src/components/Accordion/accordion.scss

Jira Link: [STR-1171](https://storyblok.atlassian.net/browse/STR-1171)
1. Open a story
1. Add a group field-type
1. Add a Datetime field type
1. Associate the Datetime to the group
1. Add other field types after the group
1. Save the schema
1. Go to the content form
1. Click on the Datetime field-type
1. The date picker should be displayed on top of the fields below

bugfix(str-1171): Support Ticket [SD-91] user is not able to see date/time fields as they cannot scroll down

---

src/components/Button/SbButton.vue
src/components/Button/button.scss

Checkout the branch `bugfix/button-icons-loading-state` and test if the buttons are working normally in the app. An example (Space settings "Save" button and Story "Publish" button):
https://user-images.githubusercontent.com/26799272/183146380-ba331fa4-54ed-4379-a415-d3b20c2929eb.mov
- Kept the rendering of the loading along with the other button elements
- Refactored the button style file to be more readable
- 
This behavior was introduced after @lisilinhart refactored the component to be a template instead of render function.

Bugfix: fix button width when on loading state

---

src/components/Menu/index.js

Jira Link: [STR-277](https://storyblok.atlassian.net/browse/STR-277)
The best scenario to test this change is described on the ticket
- Introduces a new prop to `SbMenu` to prevent focusing the menu item when opening it

fix(str-277)

---

src/components/Select/Select.stories.js
src/components/Select/components/SelectInner.vue
src/components/Select/components/SelectListItem.vue
src/components/Select/select.scss

Jira Link: [ON-742](https://storyblok.atlassian.net/browse/ON-742)
Go [here](https://storyblok-design-system-git-task-add-icon-a20600-storyblok-com.vercel.app/?path=/story/design-system-components-form-sbselect--options-with-icon) and check the options with icons
- add the possibility to use icons on select options
- 
-

ON-742: Add icon to select options

---

src/components/DataTable/components/SbDataTableActions.js

This change is required by [this](https://github.com/storyblok/storyfront/pull/2389) _storyfront_ PR
Jira Link: [WORK-499](https://storyblok.atlassian.net/browse/WORK-499)
- Introduce data-testids to SBDatatableActions for e2e testing purposes

test(work-499): introduce data-testids to SbDataTableActions buttons

---

src/components/FormItem/FormItem.stories.js
src/components/FormItem/SbFormItem.vue
src/components/FormItem/form-item.scss

Jira Link: [STR-1264](url)
Check here with different icons:
https://storyblok-design-system-git-feat-str-1264-1a7066-storyblok-com.vercel.app/?path=/story/design-system-components-form-sbformitem--with-icon
- add possibility to show icon on the right of SbFormItem's label element
- 
-

Feat/STR-1264: Add possibility of add icon to SbFormItem

---

src/components/BlockUI/BlockUi.vue
src/components/BlockUI/index.js

Jira Link: -
Compare:
- https://blok.ink/?path=/story/design-system-components-sbloading--default&args=uiBlock:true
- https://storyblok-design-system-git-refactor-ar-10-57e812-storyblok-com.vercel.app/?path=/story/design-system-components-sbloading--default&args=uiBlock:true
- uses the template syntax instead
- 
-

refactor: sbBlock UI to template syntax

---

src/components/AvatarGroup/SbAvatarGroup.vue
src/components/AvatarGroup/components/SbMoreAvatars.vue

Jira Link: [ON-857](https://storyblok.atlassian.net/browse/ON-857)
Since no new feature (or feature change) is being introduced in this PR, there is no specific behavior to test.
Just make sure the component still works as in production 🙂 
No new behavior, the component just sends more data in the click event payload. _(for an additional external need)_
Linked to [a PR on the _storyfront_ repo](https://github.com/storyblok/storyfront/pull/2625)

fix(on-857): adds more data to SbMoreAvatars click event payload

---

src/lib/internal-icons.js

Update icon 'square-warning'
Jira Link: [WORK-718](https://storyblok.atlassian.net/browse/WORK-718)
Update icon in DS:
Before: 
Now:

Subtask(work-718): update icon square-warning

---

src/components/Minibrowser/components/MinibrowserListItem.vue

Jira Link: [STR-1356](https://github.com/storyblok/storyfront/pull/2885)
This may only make sense in the context of the [PR](https://github.com/storyblok/storyfront/pull/2885) on storyfront. This just adds keyboard navigation support.

feat(str-1356): improve focus visible and interactions

---

src/lib/internal-icons.js

Jira Link: [ON-905](https://storyblok.atlassian.net/browse/ON-905)
- go to [design system icons](https://blok.ink/?path=/story/design-system-components-sbicon--all-icons)
- check there is a new space-pictogram

feat(ON-905): add space-pictogram

---

src/components/Minibrowser/components/MinibrowserListItem.vue

Jira Link: These are changes Lisi requested on [this PR](https://github.com/storyblok/storyfront/pull/2885)
- 
- 
-

feat(str-1356): add to prop to minibrowser item

---

src/components/Sidebar/Sidebar.stories.js
src/components/Sidebar/Sidebar.vue
src/components/Sidebar/components/ListItem.vue

Reverts storyblok/storyblok-design-system#360

Revert "feat(AR-61): 💄 adds redirection to spaces list logic on header logo click"

---

src/components/Sidebar/Sidebar.vue

Jira Link: [ON-993]
opens the sidebar fully on mobile screen sizes
- 
- 
- 
[ON-993]: https://storyblok.atlassian.net/browse/ON-993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ON-993): sidebar on mobile

---

src/components/DataTable/components/SbDataTableBodyRow.vue

Jira Link: [WORK-293](https://storyblok.atlassian.net/browse/WORK-293)
- add `data-testid` to `SbDataTable` checkbox 
[WORK-293]: https://storyblok.atlassian.net/browse/WORK-293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

:adhesive_bandage: feat(work-283): add data-testid to datatable checkbox

---

src/assets/styles/_sizes.scss
stories/Design/Spacing/Spacing.stories.js
stories/Design/Spacing/spacing.scss

Jira Link: - 
- new global spacing helpers for padding and margin
- 
- 
-

chore: define spacing helpers

---

src/components/BlockUI/BlockUi.vue
src/components/BlockUI/block.scss
src/components/Modal/SbModal.vue

Jira Link: [STR-1606](https://storyblok.atlassian.net/browse/STR-1606)
Logic was previously inverted 😆 now should be the correct one
- 
- 
- 
[STR-1606]: https://storyblok.atlassian.net/browse/STR-1606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(str-1606): 🐛   invert logic for modal padding

---

src/components/Pagination/pagination.scss

Jira Link: [ON-994](https://storyblok.atlassian.net/jira/software/c/projects/ON/boards/10?modal=detail&selectedIssue=ON-994)
https://github.com/storyblok/storyblok-design-system/assets/39567763/5dcc101e-3bac-476e-be72-019c2012f2ed
https://github.com/storyblok/storyblok-design-system/assets/39567763/4ff67730-a932-4e65-b992-ae1275333545
- Enhances mobile visibility of the select field and maintains two-row separation from the paginator for improved user experience.
[ON-994]: https://storyblok.atlassian.net/browse/ON-994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Bugfix: pagination select field responsiveness

---

src/components/Select/Select.stories.js
src/components/Select/Select.vue
src/components/Select/components/SelectInner.vue
src/components/Select/components/SelectInnerTag.vue

In this PR we added a tag counter for when the user selects more than one option, thus making the layout cleaner.
Jira Link: [WORK-1057](https://storyblok.atlassian.net/browse/WORK-1057)
Go to > Menu > Form > SbSelect > Multiple With Count Labels
Check if it works!
[WORK-1057]: https://storyblok.atlassian.net/browse/WORK-1057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(work-1057): add tag count in multiple select

---

src/assets/styles/global.scss
src/components/Heading/Heading.stories.js
src/components/Heading/SbHeading.vue
src/components/Heading/__tests__/Heading.spec.js
src/components/Heading/heading.scss
src/components/Heading/index.js
src/components/Heading/lib.js

The new SbHeading element. This component should replace the use of heading elements.

feat(heading): creating the new SbHeading element

---

src/components/DataTable/components/SbDataTableActions.vue
src/components/Modal/components/SbModalCloseButton.vue

In this PR we added data-testid in table actions.
Jira Link: [work-1292](https://storyblok.atlassian.net/browse/WORK-1292)
Go to Menu > Data > SbDataTable > Actions Menu
Select one item and check if the actions menu has any data-testid.

feat(work-1292): add data-testid in table actions

---

src/components/DataTable/components/SbDataTableBody.vue
src/components/DataTable/components/SbDataTableColumn.vue
src/components/DataTable/components/SbDataTableHeader.vue
src/components/DataTable/index.js

Jira Link: [WORK-1344](https://storyblok.atlassian.net/browse/WORK-1344)
This does not need testing at all apart from the QA analysis from a E2E test creation standpoint
No behavior changes.
[WORK-1344]: https://storyblok.atlassian.net/browse/WORK-1344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(work-1344): introduce data-testids to SbDataTable components

---

src/components/Badge/SbBadge.vue
src/components/Modal/SbModal.vue

Jira Link: [WORK-1296](https://storyblok.atlassian.net/browse/WORK-1296)
No test needed.
- Updated `data-testid` variables case
- No behavior changes
[WORK-1296]: https://storyblok.atlassian.net/browse/WORK-1296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(work-1342): fix data-testid case

---

src/components/Minibrowser/components/MinibrowserListItem.vue
src/components/Minibrowser/minibrowser.scss

Jira Link: [STR-2023](https://storyblok.atlassian.net/browse/STR-2023)
Content browser will be getting the scheduled icon. This will work together with this PR: [PR-STR-2023](https://github.com/storyblok/storyfront/pull/4708)
[STR-2023]: https://storyblok.atlassian.net/browse/STR-2023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(str-2023): add icon slot

---

src/assets/styles/_colors.scss
src/assets/styles/_sizes.scss
src/assets/styles/_typography.scss
src/assets/styles/helper-classes.scss
stories/Design/Spacing/Spacing.stories.js

Jira Link: INT-1085
to improve the import of the variables only, we need to extract the classes from them
- 
- 
-

fix(INT-1085): extract the helper classes to a separate file

---

src/components/Datepicker/Datepicker.stories.js
src/components/Datepicker/Datepicker.vue
src/components/Datepicker/__tests__/Datepicker.spec.js
src/components/Datepicker/__tests__/DatepickerTime.spec.js
src/components/Datepicker/components/DatepickerDays.vue
src/components/Datepicker/components/DatepickerFakeInput.vue
src/components/Datepicker/components/DatepickerHeader.vue
src/components/Datepicker/components/DatepickerMonths.vue
src/components/Datepicker/components/DatepickerTime.vue
src/components/Datepicker/components/DatepickerWeek.vue
src/components/Datepicker/components/DatepickerYears.vue
src/components/Datepicker/datepicker.scss
src/components/Datepicker/utils.ts

Jira Link: [INT-1065](https://storyblok.atlassian.net/browse/INT-1065)
<p>
<em>Before this PR</em>
<br>
</p>
<p>
<em>After this PR</em>
<br>
</p>
<p>
<em>Before this PR</em>
<br>
</p>
<p>
<em>After this PR</em>
<br>
</p>
To see the placeholder you need to click on the `Clear` button.
Default placeholder for:
```js
date: 'YYYY-MM-DD',
datetime: 'YYYY-MM-DD hh:mm',
daterange: 'YYYY-MM-DD - YYYY-MM-DD'
```
<p>
</p>
https://github.com/storyblok/storyblok-design-system/assets/40925579/906b2f37-e267-4065-86fa-11f085e67077
- Now we have the range selection feature
- Styles updates
- I need to refactor the unit tests
- Test only in the storybook preview, as an integration task for V2 was created to resolve possible incompatibility issues
[INT-1065]: …

int-1065: Datepicker style updates + Daterange feature

---

src/components/TextField/SbTextField.vue
src/components/TextField/TextField.stories.js

When fixing the bug described in the linked ticket, we realized the need to add the auto grow option to SbTextField with the textarea type.
Jira Link: [WORK-1517](https://storyblok.atlassian.net/browse/WORK-1517)
[WORK-1517]: https://storyblok.atlassian.net/browse/WORK-1517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(work-1517): add auto grow in textarea

---

.github/workflows/release-next.yml
.github/workflows/release.yml
src/assets/styles/global.scss
src/assets/styles/mixins.scss
src/assets/styles/variables.scss
src/components/Datepicker/datepicker.scss
src/components/EmptyState/empty.scss
src/components/Menu/MenuGroup.vue
src/components/Menu/menu.scss
src/components/Minibrowser/minibrowser.scss
src/components/Select/components/select-inner.scss
src/components/Select/select.scss
src/components/Sidebar/sidebar.scss
src/components/Tag/tag.scss
src/components/TextField/textfield.scss
src/components/Toggle/toggle.scss
src/components/Tooltip/tooltip.scss
stories/Design/Colors/components/ColorTile.vue
stories/Design/Typography/typography.scss

This releases the changes from the last release

chore: update release changes

---

stories/Design/Typography/Typography.stories.ts

chore: remove duplicate text color
